# disable blank issue creation
blank_issues_enabled: false

# direct users to appropriate channels for discussion
contact_links:
  - name: Gravwell Community Support
    url: https://discord.com/invite/gravwell
    about: Please ask and answer questions here.
